__title__ = 'mindsdb_datasources'
__package_name__ = 'mindsdb_datasources'
__version__ = '1.8.0'
__description__ = "Datasources for mindsdb"
__email__ = "jorge@mindsdb.com"
__author__ = 'MindsDB Inc'
__github__ = 'https://github.com/mindsdb/datasources'
__pypi__ = 'https://pypi.org/project/mindsdb_datasources'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2018- mindsdb'
